name : Blog API ci

env:
  DB_NAME: ${ secrets.DB_NAME }
  DB_USER: ${ secrets.DB_USER }
  DB_PASSWORD: ${ secrets.DB_PASSWORD }
  DATABASE_URL: ${ secrets.DATABASE_URL }
  TEST_DATABASE_URL: ${ secrets.TEST_DATABASE_URL }
  SECRET_KEY: ${ secrets.SECRET_KEY }

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repositroy
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run:
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run:
        python -m pytest
